{"url": "https://api.github.com/repos/tensorflow/tensorflow/issues/5735", "repository_url": "https://api.github.com/repos/tensorflow/tensorflow", "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/5735/labels{/name}", "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/5735/comments", "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/5735/events", "html_url": "https://github.com/tensorflow/tensorflow/issues/5735", "id": 190581713, "node_id": "MDU6SXNzdWUxOTA1ODE3MTM=", "number": 5735, "title": "einsum: \"ij,ji->\" rasing error.", "user": {"login": "weinbe58", "id": 10360423, "node_id": "MDQ6VXNlcjEwMzYwNDIz", "avatar_url": "https://avatars2.githubusercontent.com/u/10360423?v=4", "gravatar_id": "", "url": "https://api.github.com/users/weinbe58", "html_url": "https://github.com/weinbe58", "followers_url": "https://api.github.com/users/weinbe58/followers", "following_url": "https://api.github.com/users/weinbe58/following{/other_user}", "gists_url": "https://api.github.com/users/weinbe58/gists{/gist_id}", "starred_url": "https://api.github.com/users/weinbe58/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/weinbe58/subscriptions", "organizations_url": "https://api.github.com/users/weinbe58/orgs", "repos_url": "https://api.github.com/users/weinbe58/repos", "events_url": "https://api.github.com/users/weinbe58/events{/privacy}", "received_events_url": "https://api.github.com/users/weinbe58/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 473172988, "node_id": "MDU6TGFiZWw0NzMxNzI5ODg=", "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:bug/performance", "name": "type:bug/performance", "color": "159b2e", "default": false}], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 7, "created_at": "2016-11-20T20:34:25Z", "updated_at": "2017-02-09T22:02:02Z", "closed_at": "2016-11-20T22:10:25Z", "author_association": "NONE", "body_html": "<p>Hi I'm running Linux-64 bit os and I'm getting the following error after running:</p>\n<pre><code>import tensorflow as tf\nI = tf.constant([[1,0,0],[0,1,0],[0,0,1]])\nII_tr = tf.einsum('ij,ji-&gt;',I,I)\nwith tf.Session() as sess:\n\tres = sess.run(II_tr)\n\tprint res\n</code></pre>\n<p><code>AssertionError: Indices have incorrect format: ij,ji-&gt;</code> Clearly the result here should be 3.</p>", "body_text": "Hi I'm running Linux-64 bit os and I'm getting the following error after running:\nimport tensorflow as tf\nI = tf.constant([[1,0,0],[0,1,0],[0,0,1]])\nII_tr = tf.einsum('ij,ji->',I,I)\nwith tf.Session() as sess:\n\tres = sess.run(II_tr)\n\tprint res\n\nAssertionError: Indices have incorrect format: ij,ji-> Clearly the result here should be 3.", "body": "Hi I'm running Linux-64 bit os and I'm getting the following error after running:\r\n\r\n```\r\nimport tensorflow as tf\r\nI = tf.constant([[1,0,0],[0,1,0],[0,0,1]])\r\nII_tr = tf.einsum('ij,ji->',I,I)\r\nwith tf.Session() as sess:\r\n\tres = sess.run(II_tr)\r\n\tprint res\r\n```\r\n`AssertionError: Indices have incorrect format: ij,ji->` Clearly the result here should be 3. \r\n\r\n\r\n"}