{"url": "https://api.github.com/repos/tensorflow/tensorflow/issues/21695", "repository_url": "https://api.github.com/repos/tensorflow/tensorflow", "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/21695/labels{/name}", "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/21695/comments", "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/21695/events", "html_url": "https://github.com/tensorflow/tensorflow/issues/21695", "id": 351773564, "node_id": "MDU6SXNzdWUzNTE3NzM1NjQ=", "number": 21695, "title": "TensorFlow not logging any event files, tensorboard showing nothing", "user": {"login": "jingw222", "id": 5494367, "node_id": "MDQ6VXNlcjU0OTQzNjc=", "avatar_url": "https://avatars2.githubusercontent.com/u/5494367?v=4", "gravatar_id": "", "url": "https://api.github.com/users/jingw222", "html_url": "https://github.com/jingw222", "followers_url": "https://api.github.com/users/jingw222/followers", "following_url": "https://api.github.com/users/jingw222/following{/other_user}", "gists_url": "https://api.github.com/users/jingw222/gists{/gist_id}", "starred_url": "https://api.github.com/users/jingw222/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/jingw222/subscriptions", "organizations_url": "https://api.github.com/users/jingw222/orgs", "repos_url": "https://api.github.com/users/jingw222/repos", "events_url": "https://api.github.com/users/jingw222/events{/privacy}", "received_events_url": "https://api.github.com/users/jingw222/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 386191887, "node_id": "MDU6TGFiZWwzODYxOTE4ODc=", "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/stat:awaiting%20response", "name": "stat:awaiting response", "color": "f4b400", "default": false}], "state": "closed", "locked": false, "assignee": {"login": "karmel", "id": 667809, "node_id": "MDQ6VXNlcjY2NzgwOQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/667809?v=4", "gravatar_id": "", "url": "https://api.github.com/users/karmel", "html_url": "https://github.com/karmel", "followers_url": "https://api.github.com/users/karmel/followers", "following_url": "https://api.github.com/users/karmel/following{/other_user}", "gists_url": "https://api.github.com/users/karmel/gists{/gist_id}", "starred_url": "https://api.github.com/users/karmel/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/karmel/subscriptions", "organizations_url": "https://api.github.com/users/karmel/orgs", "repos_url": "https://api.github.com/users/karmel/repos", "events_url": "https://api.github.com/users/karmel/events{/privacy}", "received_events_url": "https://api.github.com/users/karmel/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "karmel", "id": 667809, "node_id": "MDQ6VXNlcjY2NzgwOQ==", "avatar_url": "https://avatars1.githubusercontent.com/u/667809?v=4", "gravatar_id": "", "url": "https://api.github.com/users/karmel", "html_url": "https://github.com/karmel", "followers_url": "https://api.github.com/users/karmel/followers", "following_url": "https://api.github.com/users/karmel/following{/other_user}", "gists_url": "https://api.github.com/users/karmel/gists{/gist_id}", "starred_url": "https://api.github.com/users/karmel/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/karmel/subscriptions", "organizations_url": "https://api.github.com/users/karmel/orgs", "repos_url": "https://api.github.com/users/karmel/repos", "events_url": "https://api.github.com/users/karmel/events{/privacy}", "received_events_url": "https://api.github.com/users/karmel/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 4, "created_at": "2018-08-18T00:25:36Z", "updated_at": "2018-11-08T17:32:00Z", "closed_at": "2018-09-28T20:58:31Z", "author_association": "NONE", "body_html": "<p>I'm currently running <code>TensorFlow 1.10.0</code>. My custom estimator is created with <code>tf.estimator.Estimator</code>, and run without a glitch. However, I don't find any event files under <code>model_dir </code>, and TensorBoard simply shows nothing.</p>\n<p>Here's how I setup my estimator:</p>\n<pre><code>classifier= tf.estimator.Estimator(\n    model_fn=lr_model_fn, model_dir=PATH)\n</code></pre>\n<p>and I open TensorBoard via <code>tensorboard --logdir=tf_models/ --host=127.0.0.1</code> where <code>tf_models</code> is the dir <code>PATH</code>.</p>\n<p>Files logged in <code>model_dir </code> include <code>checkpoint</code>, <code>graph.pbtxt</code>, <code>model.ckpt-*</code>, etc. No <code>events.out.tfevents*</code> files reside there. Is this normal? Did I have something misconfigured?</p>\n<p>EDIT:<br>\nIt seems that it only outputs <code>events.out.tfevents.*</code> file the very first time in a Jupyter session. If I clean up the PATH <code>model_dir</code> and re-train the model whatever times afterwards, there's always a events file missing there. And I have to restart Jupyter to make it work again. Is this a bug or something?</p>", "body_text": "I'm currently running TensorFlow 1.10.0. My custom estimator is created with tf.estimator.Estimator, and run without a glitch. However, I don't find any event files under model_dir , and TensorBoard simply shows nothing.\nHere's how I setup my estimator:\nclassifier= tf.estimator.Estimator(\n    model_fn=lr_model_fn, model_dir=PATH)\n\nand I open TensorBoard via tensorboard --logdir=tf_models/ --host=127.0.0.1 where tf_models is the dir PATH.\nFiles logged in model_dir  include checkpoint, graph.pbtxt, model.ckpt-*, etc. No events.out.tfevents* files reside there. Is this normal? Did I have something misconfigured?\nEDIT:\nIt seems that it only outputs events.out.tfevents.* file the very first time in a Jupyter session. If I clean up the PATH model_dir and re-train the model whatever times afterwards, there's always a events file missing there. And I have to restart Jupyter to make it work again. Is this a bug or something?", "body": "I'm currently running `TensorFlow 1.10.0`. My custom estimator is created with `tf.estimator.Estimator`, and run without a glitch. However, I don't find any event files under `model_dir `, and TensorBoard simply shows nothing.\r\n\r\nHere's how I setup my estimator:\r\n```\r\nclassifier= tf.estimator.Estimator(\r\n    model_fn=lr_model_fn, model_dir=PATH)\r\n```\r\nand I open TensorBoard via `tensorboard --logdir=tf_models/ --host=127.0.0.1` where `tf_models` is the dir `PATH`.\r\n\r\nFiles logged in `model_dir ` include `checkpoint`, `graph.pbtxt`, `model.ckpt-*`, etc. No `events.out.tfevents*` files reside there. Is this normal? Did I have something misconfigured?\r\n\r\nEDIT: \r\nIt seems that it only outputs `events.out.tfevents.*` file the very first time in a Jupyter session. If I clean up the PATH `model_dir` and re-train the model whatever times afterwards, there's always a events file missing there. And I have to restart Jupyter to make it work again. Is this a bug or something?"}