{"url": "https://api.github.com/repos/tensorflow/tensorflow/issues/6694", "repository_url": "https://api.github.com/repos/tensorflow/tensorflow", "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/6694/labels{/name}", "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/6694/comments", "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/6694/events", "html_url": "https://github.com/tensorflow/tensorflow/issues/6694", "id": 199197885, "node_id": "MDU6SXNzdWUxOTkxOTc4ODU=", "number": 6694, "title": "Why cannot I import the tpprof module?", "user": {"login": "eduOS", "id": 8926535, "node_id": "MDQ6VXNlcjg5MjY1MzU=", "avatar_url": "https://avatars0.githubusercontent.com/u/8926535?v=4", "gravatar_id": "", "url": "https://api.github.com/users/eduOS", "html_url": "https://github.com/eduOS", "followers_url": "https://api.github.com/users/eduOS/followers", "following_url": "https://api.github.com/users/eduOS/following{/other_user}", "gists_url": "https://api.github.com/users/eduOS/gists{/gist_id}", "starred_url": "https://api.github.com/users/eduOS/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/eduOS/subscriptions", "organizations_url": "https://api.github.com/users/eduOS/orgs", "repos_url": "https://api.github.com/users/eduOS/repos", "events_url": "https://api.github.com/users/eduOS/events{/privacy}", "received_events_url": "https://api.github.com/users/eduOS/received_events", "type": "User", "site_admin": false}, "labels": [], "state": "closed", "locked": false, "assignee": null, "assignees": [], "milestone": null, "comments": 1, "created_at": "2017-01-06T13:37:47Z", "updated_at": "2017-01-06T14:15:20Z", "closed_at": "2017-01-06T14:15:20Z", "author_association": "NONE", "body_html": "<p>From <a href=\"https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/tfprof/python/tools/tfprof/tfprof_logger.py#L30\">this line</a> I get to know that the new added profile tool is imported, but it seems strange: 1) it cannot be imported from the interactive interface; 2) and when mnist is run it raise the same error saying <code>ImportError: cannot import name 'tfprof_log_pb2'</code>. What happened for the newly added feature?</p>", "body_text": "From this line I get to know that the new added profile tool is imported, but it seems strange: 1) it cannot be imported from the interactive interface; 2) and when mnist is run it raise the same error saying ImportError: cannot import name 'tfprof_log_pb2'. What happened for the newly added feature?", "body": "From [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/tfprof/python/tools/tfprof/tfprof_logger.py#L30) I get to know that the new added profile tool is imported, but it seems strange: 1) it cannot be imported from the interactive interface; 2) and when mnist is run it raise the same error saying `ImportError: cannot import name 'tfprof_log_pb2'`. What happened for the newly added feature?"}