{"url": "https://api.github.com/repos/pytorch/pytorch/issues/comments/376262831", "html_url": "https://github.com/pytorch/pytorch/pull/4577#issuecomment-376262831", "issue_url": "https://api.github.com/repos/pytorch/pytorch/issues/4577", "id": 376262831, "node_id": "MDEyOklzc3VlQ29tbWVudDM3NjI2MjgzMQ==", "user": {"login": "ezyang", "id": 13564, "node_id": "MDQ6VXNlcjEzNTY0", "avatar_url": "https://avatars0.githubusercontent.com/u/13564?v=4", "gravatar_id": "", "url": "https://api.github.com/users/ezyang", "html_url": "https://github.com/ezyang", "followers_url": "https://api.github.com/users/ezyang/followers", "following_url": "https://api.github.com/users/ezyang/following{/other_user}", "gists_url": "https://api.github.com/users/ezyang/gists{/gist_id}", "starred_url": "https://api.github.com/users/ezyang/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/ezyang/subscriptions", "organizations_url": "https://api.github.com/users/ezyang/orgs", "repos_url": "https://api.github.com/users/ezyang/repos", "events_url": "https://api.github.com/users/ezyang/events{/privacy}", "received_events_url": "https://api.github.com/users/ezyang/received_events", "type": "User", "site_admin": false}, "created_at": "2018-03-26T18:19:42Z", "updated_at": "2018-03-26T18:19:42Z", "author_association": "CONTRIBUTOR", "body_html": "<p>Test are failing...</p>", "body_text": "Test are failing...", "body": "Test are failing..."}