{"url": "https://api.github.com/repos/pytorch/pytorch/issues/comments/372628687", "html_url": "https://github.com/pytorch/pytorch/issues/5687#issuecomment-372628687", "issue_url": "https://api.github.com/repos/pytorch/pytorch/issues/5687", "id": 372628687, "node_id": "MDEyOklzc3VlQ29tbWVudDM3MjYyODY4Nw==", "user": {"login": "apaszke", "id": 4583066, "node_id": "MDQ6VXNlcjQ1ODMwNjY=", "avatar_url": "https://avatars3.githubusercontent.com/u/4583066?v=4", "gravatar_id": "", "url": "https://api.github.com/users/apaszke", "html_url": "https://github.com/apaszke", "followers_url": "https://api.github.com/users/apaszke/followers", "following_url": "https://api.github.com/users/apaszke/following{/other_user}", "gists_url": "https://api.github.com/users/apaszke/gists{/gist_id}", "starred_url": "https://api.github.com/users/apaszke/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/apaszke/subscriptions", "organizations_url": "https://api.github.com/users/apaszke/orgs", "repos_url": "https://api.github.com/users/apaszke/repos", "events_url": "https://api.github.com/users/apaszke/events{/privacy}", "received_events_url": "https://api.github.com/users/apaszke/received_events", "type": "User", "site_admin": false}, "created_at": "2018-03-13T11:07:06Z", "updated_at": "2018-03-13T11:07:06Z", "author_association": "MEMBER", "body_html": "<p>The model definition in <code>torchvision</code> should be fine, but what's happening here doesn't look like a user error to me. Not sure why aren't we triggering the version checks.</p>", "body_text": "The model definition in torchvision should be fine, but what's happening here doesn't look like a user error to me. Not sure why aren't we triggering the version checks.", "body": "The model definition in `torchvision` should be fine, but what's happening here doesn't look like a user error to me. Not sure why aren't we triggering the version checks."}