{"url": "https://api.github.com/repos/pytorch/pytorch/issues/comments/381233675", "html_url": "https://github.com/pytorch/pytorch/issues/6546#issuecomment-381233675", "issue_url": "https://api.github.com/repos/pytorch/pytorch/issues/6546", "id": 381233675, "node_id": "MDEyOklzc3VlQ29tbWVudDM4MTIzMzY3NQ==", "user": {"login": "pjh5", "id": 6456020, "node_id": "MDQ6VXNlcjY0NTYwMjA=", "avatar_url": "https://avatars1.githubusercontent.com/u/6456020?v=4", "gravatar_id": "", "url": "https://api.github.com/users/pjh5", "html_url": "https://github.com/pjh5", "followers_url": "https://api.github.com/users/pjh5/followers", "following_url": "https://api.github.com/users/pjh5/following{/other_user}", "gists_url": "https://api.github.com/users/pjh5/gists{/gist_id}", "starred_url": "https://api.github.com/users/pjh5/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/pjh5/subscriptions", "organizations_url": "https://api.github.com/users/pjh5/orgs", "repos_url": "https://api.github.com/users/pjh5/repos", "events_url": "https://api.github.com/users/pjh5/events{/privacy}", "received_events_url": "https://api.github.com/users/pjh5/received_events", "type": "User", "site_admin": false}, "created_at": "2018-04-13T19:08:29Z", "updated_at": "2018-04-13T19:08:29Z", "author_association": "CONTRIBUTOR", "body_html": "<p>Don't use <a href=\"https://github.com/caffe2/caffe2\">https://github.com/caffe2/caffe2</a> ; it is no longer updated. Can you verify that this error occurs when you do a clean install on the latest code from <a href=\"https://github.com/pytorch/pytorch\">https://github.com/pytorch/pytorch</a> ?</p>\n<p>Can you post the output of the 'cmake' command?</p>", "body_text": "Don't use https://github.com/caffe2/caffe2 ; it is no longer updated. Can you verify that this error occurs when you do a clean install on the latest code from https://github.com/pytorch/pytorch ?\nCan you post the output of the 'cmake' command?", "body": "Don't use https://github.com/caffe2/caffe2 ; it is no longer updated. Can you verify that this error occurs when you do a clean install on the latest code from https://github.com/pytorch/pytorch ?\r\n\r\nCan you post the output of the 'cmake' command?"}