{"url": "https://api.github.com/repos/tensorflow/tensorflow/issues/10982", "repository_url": "https://api.github.com/repos/tensorflow/tensorflow", "labels_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/10982/labels{/name}", "comments_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/10982/comments", "events_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/10982/events", "html_url": "https://github.com/tensorflow/tensorflow/issues/10982", "id": 237824530, "node_id": "MDU6SXNzdWUyMzc4MjQ1MzA=", "number": 10982, "title": "python mnist_softmax_xla.py run failure", "user": {"login": "zhangdingfei", "id": 20080419, "node_id": "MDQ6VXNlcjIwMDgwNDE5", "avatar_url": "https://avatars0.githubusercontent.com/u/20080419?v=4", "gravatar_id": "", "url": "https://api.github.com/users/zhangdingfei", "html_url": "https://github.com/zhangdingfei", "followers_url": "https://api.github.com/users/zhangdingfei/followers", "following_url": "https://api.github.com/users/zhangdingfei/following{/other_user}", "gists_url": "https://api.github.com/users/zhangdingfei/gists{/gist_id}", "starred_url": "https://api.github.com/users/zhangdingfei/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/zhangdingfei/subscriptions", "organizations_url": "https://api.github.com/users/zhangdingfei/orgs", "repos_url": "https://api.github.com/users/zhangdingfei/repos", "events_url": "https://api.github.com/users/zhangdingfei/events{/privacy}", "received_events_url": "https://api.github.com/users/zhangdingfei/received_events", "type": "User", "site_admin": false}, "labels": [{"id": 473173351, "node_id": "MDU6TGFiZWw0NzMxNzMzNTE=", "url": "https://api.github.com/repos/tensorflow/tensorflow/labels/type:build/install", "name": "type:build/install", "color": "159b2e", "default": false}], "state": "closed", "locked": false, "assignee": {"login": "hpucha", "id": 9665833, "node_id": "MDQ6VXNlcjk2NjU4MzM=", "avatar_url": "https://avatars2.githubusercontent.com/u/9665833?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hpucha", "html_url": "https://github.com/hpucha", "followers_url": "https://api.github.com/users/hpucha/followers", "following_url": "https://api.github.com/users/hpucha/following{/other_user}", "gists_url": "https://api.github.com/users/hpucha/gists{/gist_id}", "starred_url": "https://api.github.com/users/hpucha/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hpucha/subscriptions", "organizations_url": "https://api.github.com/users/hpucha/orgs", "repos_url": "https://api.github.com/users/hpucha/repos", "events_url": "https://api.github.com/users/hpucha/events{/privacy}", "received_events_url": "https://api.github.com/users/hpucha/received_events", "type": "User", "site_admin": false}, "assignees": [{"login": "hpucha", "id": 9665833, "node_id": "MDQ6VXNlcjk2NjU4MzM=", "avatar_url": "https://avatars2.githubusercontent.com/u/9665833?v=4", "gravatar_id": "", "url": "https://api.github.com/users/hpucha", "html_url": "https://github.com/hpucha", "followers_url": "https://api.github.com/users/hpucha/followers", "following_url": "https://api.github.com/users/hpucha/following{/other_user}", "gists_url": "https://api.github.com/users/hpucha/gists{/gist_id}", "starred_url": "https://api.github.com/users/hpucha/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/hpucha/subscriptions", "organizations_url": "https://api.github.com/users/hpucha/orgs", "repos_url": "https://api.github.com/users/hpucha/repos", "events_url": "https://api.github.com/users/hpucha/events{/privacy}", "received_events_url": "https://api.github.com/users/hpucha/received_events", "type": "User", "site_admin": false}], "milestone": null, "comments": 17, "created_at": "2017-06-22T12:09:14Z", "updated_at": "2018-04-04T19:33:54Z", "closed_at": "2018-04-04T19:33:54Z", "author_association": "NONE", "body_html": "<p>Hi,<br>\nI run python mnist_softmax_xla.py and got below failure:</p>\n<p>linux-swfm:~/workarea/test&gt; python3 mnist_softmax_xla.py<br>\n...<br>\n2017-06-22 20:02:52.685534: I tensorflow/compiler/xla/service/service.cc:191]   StreamExecutor device (1): Tesla K40m, Compute Capability 3.5<br>\n2017-06-22 20:02:57.741927: F tensorflow/compiler/xla/service/algebraic_simplifier.cc:768] Check failed: user-&gt;operand(reshape_or_broadcast_operand_index) == reshape_or_broadcast (0x7f30cc012550 vs. 0x7f30cc021490)<br>\nAborted</p>\n<p>my tensorflow version is tensorflow-1.1.0<br>\ncuda sdk: 7.5</p>", "body_text": "Hi,\nI run python mnist_softmax_xla.py and got below failure:\nlinux-swfm:~/workarea/test> python3 mnist_softmax_xla.py\n...\n2017-06-22 20:02:52.685534: I tensorflow/compiler/xla/service/service.cc:191]   StreamExecutor device (1): Tesla K40m, Compute Capability 3.5\n2017-06-22 20:02:57.741927: F tensorflow/compiler/xla/service/algebraic_simplifier.cc:768] Check failed: user->operand(reshape_or_broadcast_operand_index) == reshape_or_broadcast (0x7f30cc012550 vs. 0x7f30cc021490)\nAborted\nmy tensorflow version is tensorflow-1.1.0\ncuda sdk: 7.5", "body": "Hi,\r\nI run python mnist_softmax_xla.py and got below failure:\r\n\r\nlinux-swfm:~/workarea/test> python3 mnist_softmax_xla.py   \r\n...\r\n2017-06-22 20:02:52.685534: I tensorflow/compiler/xla/service/service.cc:191]   StreamExecutor device (1): Tesla K40m, Compute Capability 3.5\r\n2017-06-22 20:02:57.741927: F tensorflow/compiler/xla/service/algebraic_simplifier.cc:768] Check failed: user->operand(reshape_or_broadcast_operand_index) == reshape_or_broadcast (0x7f30cc012550 vs. 0x7f30cc021490)\r\nAborted\r\n\r\nmy tensorflow version is tensorflow-1.1.0\r\ncuda sdk: 7.5\r\n "}