{"url": "https://api.github.com/repos/tensorflow/tensorflow/issues/comments/242917270", "html_url": "https://github.com/tensorflow/tensorflow/issues/4030#issuecomment-242917270", "issue_url": "https://api.github.com/repos/tensorflow/tensorflow/issues/4030", "id": 242917270, "node_id": "MDEyOklzc3VlQ29tbWVudDI0MjkxNzI3MA==", "user": {"login": "akors", "id": 3023492, "node_id": "MDQ6VXNlcjMwMjM0OTI=", "avatar_url": "https://avatars0.githubusercontent.com/u/3023492?v=4", "gravatar_id": "", "url": "https://api.github.com/users/akors", "html_url": "https://github.com/akors", "followers_url": "https://api.github.com/users/akors/followers", "following_url": "https://api.github.com/users/akors/following{/other_user}", "gists_url": "https://api.github.com/users/akors/gists{/gist_id}", "starred_url": "https://api.github.com/users/akors/starred{/owner}{/repo}", "subscriptions_url": "https://api.github.com/users/akors/subscriptions", "organizations_url": "https://api.github.com/users/akors/orgs", "repos_url": "https://api.github.com/users/akors/repos", "events_url": "https://api.github.com/users/akors/events{/privacy}", "received_events_url": "https://api.github.com/users/akors/received_events", "type": "User", "site_admin": false}, "created_at": "2016-08-27T13:29:57Z", "updated_at": "2016-08-27T13:31:11Z", "author_association": "NONE", "body_html": "<p><a class=\"user-mention\" data-hovercard-type=\"user\" data-hovercard-url=\"/hovercards?user_id=19640630\" data-octo-click=\"hovercard-link-click\" data-octo-dimensions=\"link_type:self\" href=\"https://github.com/elvinpoon\">@elvinpoon</a> I answered to your question on StackOverflow, on the missing \"as\" issue.</p>\n<p>The last error, the \"no such package\" thing seems to be a new thing that has been introduced recently: you can only build <em>once</em> after configuring. If you run into errors, you have to actually repeat the configure step and the build again. I don't quite know why.</p>\n<p>In case you don't want to go through the trouble, here's my last TF build for my machine:</p>\n<p><a href=\"https://dl.dropboxusercontent.com/u/1414175/tf/tensorflow_gpu_cuda8_cdnn5.1-0.10.0rc0-6d04d60-py3-none-any.whl\" rel=\"nofollow\">https://dl.dropboxusercontent.com/u/1414175/tf/tensorflow_gpu_cuda8_cdnn5.1-0.10.0rc0-6d04d60-py3-none-any.whl</a></p>\n<p>To install, you have to rename it (or symlink) to <code>tensorflow-0.10.0rc0-py3-none-any.whl</code>, otherwise pip installation will fail.</p>\n<p>It's a few days old, but still more or less up to date.</p>", "body_text": "@elvinpoon I answered to your question on StackOverflow, on the missing \"as\" issue.\nThe last error, the \"no such package\" thing seems to be a new thing that has been introduced recently: you can only build once after configuring. If you run into errors, you have to actually repeat the configure step and the build again. I don't quite know why.\nIn case you don't want to go through the trouble, here's my last TF build for my machine:\nhttps://dl.dropboxusercontent.com/u/1414175/tf/tensorflow_gpu_cuda8_cdnn5.1-0.10.0rc0-6d04d60-py3-none-any.whl\nTo install, you have to rename it (or symlink) to tensorflow-0.10.0rc0-py3-none-any.whl, otherwise pip installation will fail.\nIt's a few days old, but still more or less up to date.", "body": "@elvinpoon I answered to your question on StackOverflow, on the missing \"as\" issue.\n\nThe last error, the \"no such package\" thing seems to be a new thing that has been introduced recently: you can only build _once_ after configuring. If you run into errors, you have to actually repeat the configure step and the build again. I don't quite know why.\n\nIn case you don't want to go through the trouble, here's my last TF build for my machine:\n\nhttps://dl.dropboxusercontent.com/u/1414175/tf/tensorflow_gpu_cuda8_cdnn5.1-0.10.0rc0-6d04d60-py3-none-any.whl\n\nTo install, you have to rename it (or symlink) to `tensorflow-0.10.0rc0-py3-none-any.whl`, otherwise pip installation will fail.\n\nIt's a few days old, but still more or less up to date.\n"}